[files]
extend-exclude = ["third_party/*", "*.svg"]

[default.extend-words]
dout = "dout"
nd = "nd"
tht = "tht"
automatical = "automatical"
strat = "strat"
entrie = "entrie"
agregate = "agregate" # since that script name is already in ginkgo-data repo

[default.extend-identifiers]
set_complex_subpsace = "set_complex_subpsace" # remove when deprecated function is gone
