name: 'Run Pre-Commit'
description: 'Run Pre-Commit'
runs:
  using: "composite"
  steps:
    - name: Checkout the latest code (shallow clone)
      uses: actions/checkout@v3
      with:
        ref: develop
    - name: Make origin/develop available
      shell: bash
      run: git fetch --depth 1 origin develop
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --from-ref develop --to-ref HEAD
