on:
  pull_request_target:
    types: [opened,synchronize]
name: OnSyncPR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  check-format:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.author_association == 'COLLABORATOR' || github.event.pull_request.author_association == 'MEMBER' || github.event.pull_request.author_association == 'OWNER'
    steps:
      - name: Checkout the latest code (shallow clone)
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Check for formatting changes
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: cp .github/check-format.sh /tmp && /tmp/check-format.sh
      - name: Upload code formatting patch
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: format.patch
  abidiff:
    runs-on: ubuntu-latest
    if: github.event.pull_request.author_association == 'COLLABORATOR' || github.event.pull_request.author_association == 'MEMBER' || github.event.pull_request.author_association == 'OWNER'
    env:
      CMAKE_FLAGS: -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=DEBUG -DGINKGO_BUILD_TESTS=OFF -DGINKGO_BUILD_EXAMPLES=OFF -DGINKGO_BUILD_BENCHMARKS=OFF -DGINKGO_BUILD_HWLOC=OFF -DGINKGO_BUILD_REFERENCE=OFF -DGINKGO_BUILD_OMP=OFF -DGINKGO_BUILD_CUDA=OFF -DGINKGO_BUILD_HIP=OFF -DGINKGO_BUILD_DPCPP=OFF
    steps:
      - name: Checkout the new code (shallow clone)
        uses: actions/checkout@v2
        with:
          path: new
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Checkout the old code (shallow clone)
        uses: actions/checkout@v2
        with:
          path: old
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Install abidiff
        run: sudo apt-get install abigail-tools
      - name: Build both libraries
        run: |
          mkdir build-new
          mkdir build-old
          cmake -B build-new new ${{ env.CMAKE_FLAGS }}
          cmake -B build-old old ${{ env.CMAKE_FLAGS }}
          cmake --build build-new -j`nproc`
          cmake --build build-old -j`nproc`
      - name: Compute abidiff
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: old/.github/abidiff.sh
      - name: Upload ABI diff
        if: failure()
        uses: actions/upload-artifact@v2
        with:
            name: abi
            path: abi.diff
  changelog-wiki-check:
    runs-on: ubuntu-latest
    steps:
      - name: check if the PR ID exists in wiki
        env:
          # it suggests the head.ref should be accessd by environment.
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        # Disable it when label contains 1:ST:skip-changelog-wiki-check or the branch name starts with release
        # need use ${{  }} evaluate to avoid special character ! as the first one
        # On the pull_request trigger, it needs to use github.event.pull_request
        # In if statement, the environment is accessed by env.variable. It can not be accessed by $variable because it is on action side not runner side.
        # The label is not updated if we only change the label and rerun the action.
        if: |
          ${{
            !contains(github.event.pull_request.labels.*.name, '1:ST:skip-changelog-wiki-check') && 
            !startsWith( env.BRANCH_NAME, 'release')
          }}
        # echo accepts "$variable" not "${variable}" from environment
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          curl https://raw.githubusercontent.com/wiki/ginkgo-project/ginkgo/Changelog.md > Changelog.md
          PR="\[\#${PR_NUMBER}\]\(https://github.com/ginkgo-project/ginkgo/(issues|pull)/${PR_NUMBER}\)
          HAS_WIKI="$(cat Changelog.md | grep -E ${PR} || echo false)"
          if [[ "${HAS_WIKI}" == "false" ]]; then
            echo "This PR does not create the corresponding entry in wiki/Changelog"
            echo "Please adds [#${PR_NUMBER}](https://github.com/ginkgo-project/ginkgo/pull/${PR_NUMBER}) in wiki/Changelog"
            exit 1
          else
            echo "Wiki already has this PR entry."
          fi
