name: Check formatting
on:
  workflow_call: 

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make origin/develop available
        shell: bash
        run: git fetch --depth 1 origin develop
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --from-ref develop --to-ref HEAD
        id: pre-commit
      - name: Comment on PR
        if: ${{ failure() && steps.pre-commit.outcome == 'failure' }}
        run: cp .github/check-format.sh /tmp && /tmp/check-format.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload code formatting patch
        if: ${{ failure() && steps.pre-commit.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: patch
          path: format.patch
