name: Check formatting
on:
  workflow_call:
    inputs:
      ref:
        description: 'The branch name to checkout'
        default: ${{ github.base_ref }}
        required: false
        type: string

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code (shallow clone)
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Run Pre-Commit Checks
        uses: ./.github/actions/run-pre-commit
        id: pre-commit
      - name: Comment on PR
        if: ${{ failure() && steps.pre-commit.outcome == 'failure' }}
        run: cp .github/check-format.sh /tmp && /tmp/check-format.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload code formatting patch
        if: ${{ failure() && steps.pre-commit.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: patch
          path: format.patch
