name: Format files
on:
  issue_comment:
    types: [created]
jobs:
  format2:
    name: format
    runs-on: ubuntu-22.04
    if: github.event.issue.pull_request != '' && github.event.comment.body == '/format' && (github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER')
    steps:
    - name: Checkout the latest code (shallow clone)
      uses: actions/checkout@v3
    - uses: ./.github/actions/run-pre-commit
      continue-on-error: true
    - name: Commit formatting changes
      run: |
        git config user.name ginkgo-bot
        git config user.email ginkgo.library@gmail.com
        git add . 
        git commit -m "Format files" || true
        git push