name: Mirroring

on:
  workflow_call:
    inputs:
      skip:
        description: 'Skip all CI'
        type: string
        default: false

jobs:
  check-skip-ci:
    runs-on: ubuntu-slim
    permissions:
     pull-requests: read
    outputs:
     skip: ${{ steps.labels.outputs.skip }}
    steps:
     - name: Check for 1:ST:SKIP_ALL_CI label
       id: labels
       env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         SKIP=$(gh pr list --repo "${{ github.repository }}" --head "${{ github.ref_name }}" --state open \
           --json labels --jq 'any(.[].labels[].name; . == "1:ST:SKIP_ALL_CI")')
         echo "skip=${SKIP}" >> "$GITHUB_OUTPUT"

  to-gitlab:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          persist-credentials: false
      - name: Push to Gitlab
        run: cp --preserve .github/mirror.sh /tmp && /tmp/mirror.sh
        env:
          BOT_KEY: ${{ secrets.GITLAB_MIRROR_PRIV_KEY }}
          BRANCH_NAME: ${{ github.ref_name }}
          GITHUB_REPO: ${{ github.repository }}
          SKIP: ${{ inputs.skip }}
